travis:
  secure:
    BINSTAR_TOKEN: Hp38W9hr6cqjvQyKc5K4bzlAldWzMR/vyJ6EHpU7cmqsXbIKWnMpXIkxuEd0ENodGmiL2yvkU1cgWn8ivyHx1nfhY9sVUCrBM+xwPKyvrLP/nVNGkT/jkjvUBOiF0xKtMAkPdC9pY2BAlrnMZN0J5Gul9gaXk+05T3z0F7o0Gl69s+bA+cfUE4/aZiCMj64+w9c3DRcytd0+kO04mNX8bI48dtuQEFSsik9QCkWitc7jfYX5WnF2hn0yXrFhaAapHrHJ9sykvJDgRGtzvsiqARkTipAZNN8xkhm3Co91I7dry1cNQMNPLHMefz03B6T+nfPm3vriG3QBFZHbmAsm9dNmcKaglrJbEv60bmvgcyapwh2MPtjXwyfcjFqSYn+K67vnt5r7r47ycWVto8Tn1x/cIM4rdqp3ti7hraDX1mSa4BPgb2DR6QXIGzkpddS58qzCvvCcEimGq8Zws+SJheuQRtiaDJoNztnx29wMF/w9d/yz4MFqr/bb4hBZNc8ORZ7MlX+hMAGi94ufY4sgf9xBjUt7Iv8wOAxbRLuDeIxP0dwfnEtNSbErlLvNahE9W085InMd5shxAnZ/4EvqalJux40WKfGxGoBVwGEgZlgdhYydvsDqM5h1I8Cb6ZiF8eOacSQYKzSi/CRvehyR1hW++wxDzBkkvB1lWVz3J4E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
