appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Q+xLqEGtK9q8KRi3LzAI0MWOOz98Z4zm11ZlMpUYSwO6oOC9flluZ5kmmjTv/2SeGRRfOdcei6p6AqVq3sAgs7QwqyrowC2kd0mhaQ8BskKTayr+GJV3zZn7IQ/lo0abwwLl0MnyJjrmZEDUqt//zweVE6d0hbOS/Dy0ofr5K2czttCUx/5FevqkscQiEO7A/3MU6n16eTpUadiYHNpRwnHcA8LDZRMEQ0CPfjJ91hqYumRsnCk3bKvyGXZK/sssYvPrl8Y6OQvtxS3F+iUVx0ZON4Q4n9v/Ple21QMo+5snzDiNSk6O90XgiFKGjpfH+aOvmVj483TmhAdnRIj40sANkdllprOn0CJJSrY0NPzt6vfFGJ0u1JBPveAtYZZe+J2jqhfGz7fRhuTa1UnP10eH6D0vQy+94Wi7rsXHeAfEKYLqzvF6Tt54wID+bjz1tyVrDwg+hXBdTfrZFaLfc4D0Va5x/+WDWVOIEx9n6AkRJP+JeItDz3U3mjonub9o3eLXi8pvhJ5uOpAmeuLIt0oRcETPhD8cy0GMOM4lSv3hMekywFCabeRrnMHytiTXCvtoQ11Di010WZLk8g7axbtSewTwTQf6gV76TJr0CV6gA9UfQMzV+RU7idonsJT+o1ekr0BMVivlg5X+l/4QUDBV7Lfo+wblcS1I4J5s0rk=}
