travis:
  secure:
    BINSTAR_TOKEN: XpPg0HjyUbP+felWg+LuKXAcwUs6TiNr1u9erchnHfdzc1/G6YlxBeT9/bpNLtML7bgSrOWWe+fo+lIepba1UAOX5/uLdfBJ/ckRX25ZF1Q/RF0GclMidNPBjIwbaseI0WGb/V5GM21RuIhsuN1p7pgcMrJxhrVZ7RJIo60aaRTu/WdJBWq8ACSYMXncZtaRvy3PeXRZZ+9eceOYTgp6idf1sZ1gl5iBEAGuLpBkdGyOaCwPWwurT8rwFFDDpGCt0P0GN5zcZgguLieY+13kTa43dPjTvDlFkb5bFev9to+9uic9FJ+t9oLfl2W7EYcpSYpH738V1iNwk194Wl/ydFw1unaN8/E4D/bhxUOQBDqJUaPjzmWOMW4tlcxhPfKuyWuKkZBMElf7bVb4YGuoZdbeK3nFLA9FwocVx771p9DztQhl/FDvH4Y3KIiZAqG57L2CrGKUWsgfe787adX7T1X+W9hmmIkN+E6yP1cAluYB0LsBgaZsTgMllvW7pnVa9TVzDeG4GgEncFinup4Lbl/bP1D9EmQuAY2rJ7MjQlm08M2aUNV2lIMIEn2L4ibf+kw+mu6NKR8NaTMUkTLOPuw/E1uYmgNrrMdNrqfWCKK2QdP0CLVXsHnQ9o3MbwCWS0mPCftbeYSKrtSiI/RQDkK2o56p2FyzETIgC6RYUb8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
